apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
  selector:
    app: rabbitmq
  type: NodePort #LoadBalancer, ClusterIP, NodePort, ...