apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: worker
  # namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
