---
# tasks file for restrict-ssh

- name: Disallow ssh via password
  replace:
    path: '/etc/ssh/sshd_config'
    regexp: 'PasswordAuthentication yes'
    replace: 'PasswordAuthentication no'
  notify: 
    - restart sshd
  tags: [config, ssh]

- name: Disallow ssh from intrnet
  replace: 
    path: '/etc/ssh/sshd_config'
    regexp: '#ListenAddress 0.0.0.0'
    replace: 'ListenAddress 172.31.16.0/20'
  notify: 
    - restart sshd
  tags: [config, ssh]

