---
# tasks file for users

- name: Ensure group "www-user" exists
  group:
    name: www-user
    state: present

- name: Prepare www users
  user:
    name: "{{ item.name }}"
    group: "www-user"
    state: present
  with_items: "{{ users_list }}"
  tags: [users]

- name: Add public ssh key
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.pubkey }}"
  with_items: "{{ users_list }}"
  tags: [users, ssh]

- name: Ansible check file exists example.
  stat:
    path: /var/www
  register: file_details
  tags: [www]

- name: Allow users edit www files
  file:
    path: /var/www
    group: "www-user"
    recurse: yes
    mode: 0774
  when: file_details.stat.exists
  tags: [users, www]
