apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  ports:
  - port: 4000
    name: for-writer
    targetPort: 4000
    protocol: TCP
  - port: 5000
    name: for-reader
    targetPort: 5000
    protocol: TCP
  selector:
    app: back
  type: ClusterIP