apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: front
  type: LoadBalancer  # ClusterIP, NodePort, ...